In [1]:
import numpy as np

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [30]:
# Task 1
arr = np.random.randint(1,21, size=(5,5))
print(f"Original Array: \n {arr}")
arr[:, 2] = 1
print(f"Array with third column as 1: \n {arr}")
# Task 2
arr = np.arange(1, 17).reshape(4, 4)
print(f"Original Array: \n {arr}")
np.fill_diagonal(arr,0)
print(f"Array with diagonal elements as 0: \n {arr}")


        
    

Original Array: 
 [[15 13 12  9  1]
 [ 7 20 16  5  7]
 [12 15 17  4 19]
 [ 1 12  9  6  3]
 [ 1  9 15 12  9]]
Array with third column as 1: 
 [[15 13  1  9  1]
 [ 7 20  1  5  7]
 [12 15  1  4 19]
 [ 1 12  1  6  3]
 [ 1  9  1 12  9]]
Original Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Array with diagonal elements as 0: 
 [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [36]:
# Task 1
arr = np.arange(1, 37).reshape((6, 6))
print(f"Original Array: \n {arr}")
print(f"Sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns: \n {arr[2:5, 1:4]}")

# Task 2
arr = np.random.randint(10, 100, size=(5,5))
print(f"Original Array: \n {arr}")
border_elements = np.concatenate((arr[0,:],arr[-1,:],arr[1:-1,0],arr[1:-1,-1],))
display(border_elements)

Original Array: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns: 
 [[14 15 16]
 [20 21 22]
 [26 27 28]]
Original Array: 
 [[47 20 25 23 30]
 [50 12 92 38 10]
 [23 54 85 62 89]
 [67 32 63 52 82]
 [91 95 55 76 37]]


array([47, 20, 25, 23, 30, 91, 95, 55, 76, 37, 50, 23, 67, 10, 89, 82],
      dtype=int32)

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [38]:
#Task 1
# Create two NumPy arrays of shape (3, 4) filled with random integers
array1 = np.random.randint(1, 11, size=(3, 4))
array2 = np.random.randint(1, 11, size=(3, 4))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)


#Task 2

# Create a NumPy array of shape (4, 4) with values from 1 to 16
array = np.arange(1, 17).reshape((4, 4))
print("Original array:")
print(array)

# Compute the row-wise and column-wise sum
row_sum = np.sum(array, axis=1)
column_sum = np.sum(array, axis=0)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(column_sum)

Array 1:
[[4 9 2 1]
 [9 6 4 3]
 [4 6 8 6]]
Array 2:
[[ 1  1  9 10]
 [ 6  6  1  6]
 [ 7  3  6 10]]
Element-wise addition:
[[ 5 10 11 11]
 [15 12  5  9]
 [11  9 14 16]]
Element-wise subtraction:
[[ 3  8 -7 -9]
 [ 3  0  3 -3]
 [-3  3  2 -4]]
Element-wise multiplication:
[[ 4  9 18 10]
 [54 36  4 18]
 [28 18 48 60]]
Element-wise division:
[[4.         9.         0.22222222 0.1       ]
 [1.5        1.         4.         0.5       ]
 [0.57142857 2.         1.33333333 0.6       ]]
Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum:
[10 26 42 58]
Column-wise sum:
[28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).