In [2]:
import numpy as np

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [3]:
# Task 1
arr = np.random.randint(1,21, size=(5,5))
print(f"Original Array: \n {arr}")
arr[:, 2] = 1
print(f"Array with third column as 1: \n {arr}")
# Task 2
arr = np.arange(1, 17).reshape(4, 4)
print(f"Original Array: \n {arr}")
np.fill_diagonal(arr,0)
print(f"Array with diagonal elements as 0: \n {arr}")


        
    

Original Array: 
 [[13  2  7  6  5]
 [ 9  5 20 16 15]
 [20 12 13  3 16]
 [18  8 20 20 14]
 [10 18  8 13 10]]
Array with third column as 1: 
 [[13  2  1  6  5]
 [ 9  5  1 16 15]
 [20 12  1  3 16]
 [18  8  1 20 14]
 [10 18  1 13 10]]
Original Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Array with diagonal elements as 0: 
 [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [4]:
# Task 1
arr = np.arange(1, 37).reshape((6, 6))
print(f"Original Array: \n {arr}")
print(f"Sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns: \n {arr[2:5, 1:4]}")

# Task 2
arr = np.random.randint(10, 100, size=(5,5))
print(f"Original Array: \n {arr}")
border_elements = np.concatenate((arr[0,:],arr[-1,:],arr[1:-1,0],arr[1:-1,-1],))
display(border_elements)

Original Array: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns: 
 [[14 15 16]
 [20 21 22]
 [26 27 28]]
Original Array: 
 [[48 24 56 76 14]
 [37 74 29 50 70]
 [65 17 72 44 83]
 [88 25 10 61 24]
 [12 76 94 10 20]]


array([48, 24, 56, 76, 14, 12, 76, 94, 10, 20, 37, 65, 88, 70, 83, 24],
      dtype=int32)

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [5]:
#Task 1
# Create two NumPy arrays of shape (3, 4) filled with random integers
array1 = np.random.randint(1, 11, size=(3, 4))
array2 = np.random.randint(1, 11, size=(3, 4))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)


#Task 2

# Create a NumPy array of shape (4, 4) with values from 1 to 16
array = np.arange(1, 17).reshape((4, 4))
print("Original array:")
print(array)

# Compute the row-wise and column-wise sum
row_sum = np.sum(array, axis=1)
column_sum = np.sum(array, axis=0)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(column_sum)

Array 1:
[[ 6  5  1  7]
 [ 7  1  3  8]
 [ 8  8  8 10]]
Array 2:
[[ 7  5  6 10]
 [ 5  5 10  3]
 [ 8  6  1  9]]
Element-wise addition:
[[13 10  7 17]
 [12  6 13 11]
 [16 14  9 19]]
Element-wise subtraction:
[[-1  0 -5 -3]
 [ 2 -4 -7  5]
 [ 0  2  7  1]]
Element-wise multiplication:
[[42 25  6 70]
 [35  5 30 24]
 [64 48  8 90]]
Element-wise division:
[[0.85714286 1.         0.16666667 0.7       ]
 [1.4        0.2        0.3        2.66666667]
 [1.         1.33333333 8.         1.11111111]]
Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum:
[10 26 42 58]
Column-wise sum:
[28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [6]:
# Task 1
arr = np.random.randint(0, 100, size = (5, 5))
print(f"Original Array: \n {arr}")
mean = np.mean(arr)
median = np.median(arr)
standard_deviation = np.std(arr)
variance = np.var(arr)
print(f"So, we got: \nMean: {mean}\nMedian: {median}\nStandard deviation: {standard_deviation}\nVariance: {variance}")


# Task 2
print("<---Task 2--->")
arr = np.arange(1, 10).reshape(3, 3)
print(f"Original Array: \n {arr}")
mean = np.mean(arr)
std_dev = np.std(arr)
norm_arr = (arr - mean) / std_dev

print(f"Normalized Array: {norm_arr}")

Original Array: 
 [[86 37  8 70 25]
 [18 14  3 80  9]
 [44 21  3 18 30]
 [15 88 24 61 90]
 [53 47 31 76 25]]
So, we got: 
Mean: 39.04
Median: 30.0
Standard deviation: 28.012111666206103
Variance: 784.6784
<---Task 2--->
Original Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized Array: [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [11]:
# Task 1
arr1 = np.random.randint(0, 100, size = (3, 3))
print(f"First 2D Array: \n {arr1}")
arr2 = np.random.randint(0, 100, size = (3,))
print(f"Second 1D Array: \n {arr2}")
# Addition by Broadcasting
arr3 = arr1 + arr2
print(f"Array after addtion by broadcasting: \n{arr3}")

# Task 2
arr1 = np.random.randint(0, 100, size = (4, 4))
print(f"First 2D Array: \n {arr1}")
arr2 = np.random.randint(0, 100, size = (4,))
print(f"Second 1D Array: \n {arr2}")
# Subtraction by Broadcasting
arr3 = arr1 - arr2
print(f"Array after subtration by broadcasting: \n{arr3}")



First 2D Array: 
 [[34 86 56]
 [32 15 59]
 [76 16 47]]
Second 1D Array: 
 [16 23 20]
Array after addtion by broadcasting: 
[[ 50 109  76]
 [ 48  38  79]
 [ 92  39  67]]
First 2D Array: 
 [[23 56 83 57]
 [69 43 91 56]
 [81  2 68 57]
 [78 63  2 26]]
Second 1D Array: 
 [23 77 53  7]
Array after subtration by broadcasting: 
[[  0 -21  30  50]
 [ 46 -34  38  49]
 [ 58 -75  15  50]
 [ 55 -14 -51  19]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [18]:
# Task 1
mtrx = np.random.randint(0, 100, size = (3, 3))
print(f"Original Matrix: \n {arr1}")
dtr = np.linalg.det(mtrx)
inv = np.linalg.inv(mtrx)
eig_val = np.linalg.eig(mtrx)
print(f"So, we got: \nThe Determinat: {dtr}\nThe Inverse: \n{inv}\nThe Eigenvalues: \n{eig_val}")


# Task 2
print("<---Task 2--->")
mtrx1 = np.random.randint(0, 100, size = (2, 3))
mtrx2 = np.random.randint(0, 100, size = (3, 2))
mat_mul = mtrx1.dot(mtrx2)
print(f"Resultant Matrix after Multiplication: \n{mat_mul}")

Original Matrix: 
 [[23 56 83 57]
 [69 43 91 56]
 [81  2 68 57]
 [78 63  2 26]]
So, we got: 
The Determinat: -20122.000000000022
The Inverse: 
[[ 0.11539608 -0.05556108 -0.01048604]
 [-0.08587616  0.04134778  0.01943147]
 [-0.08657191  0.07871981 -0.0110824 ]]
The Eigenvalues: 
EigResult(eigenvalues=array([109.16150399,   5.92891311, -31.0904171 ]), eigenvectors=array([[ 0.38409942,  0.65429173, -0.04829311],
       [ 0.60235378, -0.52447509, -0.30760558],
       [ 0.69974107, -0.54481944,  0.95028763]]))
<---Task 2--->
Resultant Matrix after Multiplication: 
[[7791 5544]
 [3489 3236]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [24]:
arr = np.arange(1, 10).reshape(3, 3)
print(f"Original: \n {arr}")
arr = arr.reshape(1, 9)
print(f"Shape(1, 9): \n {arr}")
arr = arr.reshape(9, 1)
print(f"Shape(9, 1): \n {arr}")


Original: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape(1, 9): 
 [[1 2 3 4 5 6 7 8 9]]
Shape(9, 1): 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.