In [64]:
import numpy as np

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [65]:
# Task 1
arr = np.random.randint(1,21, size=(5,5))
print(f"Original Array: \n {arr}")
arr[:, 2] = 1
print(f"Array with third column as 1: \n {arr}")
# Task 2
arr = np.arange(1, 17).reshape(4, 4)
print(f"Original Array: \n {arr}")
np.fill_diagonal(arr,0)
print(f"Array with diagonal elements as 0: \n {arr}")


        
    

Original Array: 
 [[ 5 18  8  5 16]
 [16  4  2 10 17]
 [16  9 12  1  5]
 [ 9  4  3 19 15]
 [ 2 14 10  5 15]]
Array with third column as 1: 
 [[ 5 18  1  5 16]
 [16  4  1 10 17]
 [16  9  1  1  5]
 [ 9  4  1 19 15]
 [ 2 14  1  5 15]]
Original Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Array with diagonal elements as 0: 
 [[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [66]:
# Task 1
arr = np.arange(1, 37).reshape((6, 6))
print(f"Original Array: \n {arr}")
print(f"Sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns: \n {arr[2:5, 1:4]}")

# Task 2
arr = np.random.randint(10, 100, size=(5,5))
print(f"Original Array: \n {arr}")
border_elements = np.concatenate((arr[0,:],arr[-1,:],arr[1:-1,0],arr[1:-1,-1],))
display(border_elements)

Original Array: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns: 
 [[14 15 16]
 [20 21 22]
 [26 27 28]]
Original Array: 
 [[46 67 26 35 41]
 [23 35 56 50 15]
 [98 40 61 55 39]
 [51 76 61 16 65]
 [31 73 51 43 93]]


array([46, 67, 26, 35, 41, 31, 73, 51, 43, 93, 23, 98, 51, 15, 39, 65],
      dtype=int32)

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [67]:
#Task 1
# Create two NumPy arrays of shape (3, 4) filled with random integers
array1 = np.random.randint(1, 11, size=(3, 4))
array2 = np.random.randint(1, 11, size=(3, 4))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)


#Task 2

# Create a NumPy array of shape (4, 4) with values from 1 to 16
array = np.arange(1, 17).reshape((4, 4))
print("Original array:")
print(array)

# Compute the row-wise and column-wise sum
row_sum = np.sum(array, axis=1)
column_sum = np.sum(array, axis=0)

print("Row-wise sum:")
print(row_sum)
print("Column-wise sum:")
print(column_sum)

Array 1:
[[ 5  5  3  2]
 [ 9  9  5  2]
 [10  9  3  9]]
Array 2:
[[7 7 6 2]
 [9 3 8 5]
 [8 2 9 5]]
Element-wise addition:
[[12 12  9  4]
 [18 12 13  7]
 [18 11 12 14]]
Element-wise subtraction:
[[-2 -2 -3  0]
 [ 0  6 -3 -3]
 [ 2  7 -6  4]]
Element-wise multiplication:
[[35 35 18  4]
 [81 27 40 10]
 [80 18 27 45]]
Element-wise division:
[[0.71428571 0.71428571 0.5        1.        ]
 [1.         3.         0.625      0.4       ]
 [1.25       4.5        0.33333333 1.8       ]]
Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum:
[10 26 42 58]
Column-wise sum:
[28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [68]:
# Task 1
arr = np.random.randint(0, 100, size = (5, 5))
print(f"Original Array: \n {arr}")
mean = np.mean(arr)
median = np.median(arr)
standard_deviation = np.std(arr)
variance = np.var(arr)
print(f"So, we got: \nMean: {mean}\nMedian: {median}\nStandard deviation: {standard_deviation}\nVariance: {variance}")


# Task 2
print("<---Task 2--->")
arr = np.arange(1, 10).reshape(3, 3)
print(f"Original Array: \n {arr}")
mean = np.mean(arr)
std_dev = np.std(arr)
norm_arr = (arr - mean) / std_dev

print(f"Normalized Array: {norm_arr}")

Original Array: 
 [[88 87 24 52 80]
 [18 97 79 15 67]
 [62  8 10 29 60]
 [69  3 97 35 20]
 [86 50 34 20 88]]
So, we got: 
Mean: 51.12
Median: 52.0
Standard deviation: 30.853615671424958
Variance: 951.9455999999998
<---Task 2--->
Original Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized Array: [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [69]:
# Task 1
arr1 = np.random.randint(0, 100, size = (3, 3))
print(f"First 2D Array: \n {arr1}")
arr2 = np.random.randint(0, 100, size = (3,))
print(f"Second 1D Array: \n {arr2}")
# Addition by Broadcasting
arr3 = arr1 + arr2
print(f"Array after addtion by broadcasting: \n{arr3}")

# Task 2
arr1 = np.random.randint(0, 100, size = (4, 4))
print(f"First 2D Array: \n {arr1}")
arr2 = np.random.randint(0, 100, size = (4,))
print(f"Second 1D Array: \n {arr2}")
# Subtraction by Broadcasting
arr3 = arr1 - arr2
print(f"Array after subtration by broadcasting: \n{arr3}")



First 2D Array: 
 [[46 18 29]
 [68 51  3]
 [ 1 91 29]]
Second 1D Array: 
 [32 60  5]
Array after addtion by broadcasting: 
[[ 78  78  34]
 [100 111   8]
 [ 33 151  34]]
First 2D Array: 
 [[ 8 66 82 23]
 [11 64 33 29]
 [21 96 23 47]
 [22 83  4 58]]
Second 1D Array: 
 [38 38 14 28]
Array after subtration by broadcasting: 
[[-30  28  68  -5]
 [-27  26  19   1]
 [-17  58   9  19]
 [-16  45 -10  30]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [70]:
# Task 1
mtrx = np.random.randint(0, 100, size = (3, 3))
print(f"Original Matrix: \n {mtrx}")
dtr = np.linalg.det(mtrx)
inv = np.linalg.inv(mtrx)
eig_val = np.linalg.eig(mtrx)
print(f"So, we got: \nThe Determinat: {dtr}\nThe Inverse: \n{inv}\nThe Eigenvalues: \n{eig_val}")


# Task 2
print("<---Task 2--->")
mtrx1 = np.random.randint(0, 100, size = (2, 3))
mtrx2 = np.random.randint(0, 100, size = (3, 2))
mat_mul = mtrx1.dot(mtrx2)
print(f"Resultant Matrix after Multiplication: \n{mat_mul}")

Original Matrix: 
 [[84 96 43]
 [44 68 82]
 [62 20 60]]
So, we got: 
The Determinat: 296136.00000000006
The Inverse: 
[[ 0.00823946 -0.01654645  0.01670854]
 [ 0.00825296  0.00801659 -0.01687063]
 [-0.01126509  0.0144258   0.00502472]]
The Eigenvalues: 
EigResult(eigenvalues=array([186.74513161 +0.j        ,  12.62743419+37.76670736j,
        12.62743419-37.76670736j]), eigenvectors=array([[ 0.70539455+0.j        ,  0.62528297+0.j        ,
         0.62528297-0.j        ],
       [ 0.56076467+0.j        , -0.31882062+0.4469466j ,
        -0.31882062-0.4469466j ],
       [ 0.43354529+0.j        , -0.32607605-0.44865104j,
        -0.32607605+0.44865104j]]))
<---Task 2--->
Resultant Matrix after Multiplication: 
[[6045 8902]
 [4405 8534]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [71]:
#Task 1
arr = np.arange(1, 10).reshape(3, 3)
print(f"Original: \n {arr}")
arr = arr.reshape(1, 9)
print(f"Shape(1, 9): \n {arr}")
arr = arr.reshape(9, 1)
print(f"Shape(9, 1): \n {arr}")

#Task 1
print("<---Task 2--->")
arr = np.arange(0, 25).reshape(5, 5)
print(f"Original: \n {arr}")
arr = arr.flatten()
print(f"Flattened: \n {arr}")
arr = arr.reshape(5, 5)
print(f"Shape(5, 5): \n {arr}")

Original: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape(1, 9): 
 [[1 2 3 4 5 6 7 8 9]]
Shape(9, 1): 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
<---Task 2--->
Original: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Flattened: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
Shape(5, 5): 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [72]:
# Task 1
arr1 = np.random.randint(0, 20, size = (5, 5))
print(f"Original Array: \n {arr1}")
cor_elm_arr = arr1[[0, 0, -1, -1], [0, -1, 0, -1]]  
print(f"Corner Elements: \n{cor_elm_arr}")


# Task 2
print("<---Task 2--->")
arr1 = np.random.randint(0, 20, size = (4, 4))
print(f"Original Array: \n {arr1}")
arr1[arr1 > 10] = 10
print(f"After boolean indexing to change elements greater than 10 to 10: \n{arr1}")


Original Array: 
 [[ 4 12  6 13  8]
 [19  7  9  2 16]
 [ 6  6 17 17 10]
 [ 0  7 16 13  7]
 [16 15  0 16  2]]
Corner Elements: 
[ 4  8 16  2]
<---Task 2--->
Original Array: 
 [[ 4  7  0 18]
 [ 6 15 10  0]
 [13 10  5  5]
 [ 5  7  9 14]]
After boolean indexing to change elements greater than 10 to 10: 
[[ 4  7  0 10]
 [ 6 10 10  0]
 [10 10  5  5]
 [ 5  7  9 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [92]:
# Task 1
arr1 = np.array([("Ali",20, 20.1 ), ('Sana', 2, 21.0), ('Mansi', 7, 29.0)], dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
print(f"Original Array: \n {arr1}")
arr1.sort(order="age")
print(f"Array sorted by age: \n{arr1}")

# Task 2
print("<---Task 2--->")

dt = np.dtype([('x', 'i4'), ('y', 'i4')])
data = np.array([(1, 4), (5, 6), (7, 10), (14, 29)], dtype=dt)
print(arr2)
# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original Array: 
 [('Ali', 20, 20.1) ('Sana',  2, 21. ) ('Mansi',  7, 29. )]
Array sorted by age: 
[('Sana',  2, 21. ) ('Mansi',  7, 29. ) ('Ali', 20, 20.1)]
<---Task 2--->
[( 1,  4) ( 5,  6) ( 7, 10) (14, 29)]
Euclidean distances:
[[ 0.          4.47213595  8.48528137 28.17800561]
 [ 4.47213595  0.          4.47213595 24.69817807]
 [ 8.48528137  4.47213595  0.         20.24845673]
 [28.17800561 24.69817807 20.24845673  0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [95]:
import numpy.ma as ma

# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[16 12  8 19]
 [ 2 10 12 14]
 [18 16 10  8]
 [12  6  3  1]]
Masked array:
[[-- -- 8 --]
 [2 10 -- --]
 [-- -- 10 8]
 [-- 6 3 1]]
Sum of unmasked elements: 48


In [98]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[11 13  3]
 [ 9 10 11]
 [ 7  3 18]]
Masked array:
[[-- 13 3]
 [9 -- 11]
 [7 3 --]]
Modified masked array:
[[ 7 13  3]
 [ 9  7 11]
 [ 7  3  7]]


### Well, I couldn't solve the 10th problem... Used Ai for it... Mann!! there are too many functions to remember for each function or operation.
## My tip: Google stuff first, try to solve it and learn it first, then just use Ai.
# This way you'd know what is going on with your code even when you're "vibe coding", and you won't have to bang you head with agents and pray that it gets the error fixed this iteration.